### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [amazon-science/PAE#4]
Hi,
Thanks for releasing PAE! I noticed that you mentioned in the announcement that it was fully open sourced. Are there any plans to switch to an open source/OSI-approved license?
Thanks!

**Comment by YifeiZhou02** [comment]
Hi,

Thanks for your interest in our work! Unfortunately the license is added by Amazon legal team and we are not able to change the content for this license. Apologies for the confusion!

**Comment by fakerybakery** [comment]
Makes sense, thanks!
